'''
V1.0
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user
guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the
wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user
makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''
import random

def random_list():
    random_num=[]
    n=0
    while n<=3:
        digit=random.randint(0, 9)
        random_num.append(digit)
        n += 1
    return random_num

def exit(random_number):
    print("Sorry to see you go!")
    s = [str(i) for i in (random_number)]
    random_number="".join(s)
    print("The answer was  " + random_number)
    quit()

def get_user_input(userinput):
    userinput=input("What is your guess? ")
    return userinput
    
def check_user_input(userinput, random_number):
    quit=["quit","exit"]
    if userinput.lower() in quit:
        exit(random_number)
    if len(userinput)<4 or len(userinput) >4:
        print("Your number must be a four digit number")
        print("Please try again")
        return False
    try:
        # Convert it into integer
        val = int(userinput)
        #print("Input is an integer number. Number = ", val)
        return True
    except ValueError:
        try:
            # Convert it into float
            val = float(userinput)
            print("Please enter an integer number.")
            return False
        except ValueError:
            print("Please enter an integer number.")
            return False
            
def game_engine(random_number):
   
    def test(random_number, userinput, cow, bull):
        userinput_position=0
        cow=0
        bull = 0
        '''Looping through user input to find out how many cows and bulls we have.  First I find out how many cows I have.  To do this I copied the user input
        into a scratchpad of sorts.  After we identify the cows we eliminate the digits in the userinput_scratchpad list, so that when we compare it in the next loop
        to find the bulls we can accurately account for the number of bulls.  NOTE:  When I copied the userinput into the scratchpad I had to convert it into a list or I would end up
        with a '"int" does not have a remove object' (I can't remember the exact error messager) error.'''
        userinput_scratchpad = [int(x) for x in userinput]
        while userinput_position <=3:
        # Here is the routine to count the number of cows
            userinput_digit = int(userinput[userinput_position])
            if random_number[userinput_position] == userinput_digit:
                cow += 1
                userinput_scratchpad.remove(userinput_digit)
            userinput_position += 1
        '''
        And this is the routine to count the number of bulls.  But before we do that, we need to remove all duplicates from userinput_scratchpad or we will have
        multiple bulls where there shouldn't be bulls.  The set() command will leave one remaining digit, so if there is only one digit left in userinput_scratchpad there is no
        need to test it further so we just exit the function.  If we do attempt to continue the function in the next loop we wind up with a false bull (bull = 1).
        '''
        userinput_scratchpad = list(set(userinput_scratchpad))
        if len(userinput_scratchpad)==1:
            return cow, bull
        for userinput_position in userinput_scratchpad:
            if (userinput_position in random_number):
                bull += 1
        if cow==4:
            return cow, bull
        return cow, bull
    cow=0
    bull=0
    count=0
    while cow != 4:
        userinput=0
        userinput = get_user_input(userinput)
        check = check_user_input(userinput, random_number)
        if check==False:
            continue
        result=test(random_number, userinput, cow, bull)
        print(str(result[0]) + " cow" + " " + str(result[1]) + " bull")
        cow=result[0]
        count += 1

    #code line below doesn't work for ealier python versions.
    #print(f"{result[0]} cow, {result[1]} bull")
    print("Correct! You got it right!!!")
    print("It took you " + str(count) + " tries to get it!")
    
#Game begins here with the introduction of the game and how to play.    
print("Welcome to the Cows and Bulls game!")
print("I will create a 4 digit number, 0000 - 9999, and you will guess what the number is.")
print("To help you, I will let you know how many digits you had right (\"Cows\") and how many you had wrong (\"Bulls\").")
# print("To help you, I will let you know how many digits you had right (\"Cows\") and how many you had right but in the wrong place (\"Bulls\").")
print("If you give up, type \"quit\", or \"exit\" to end the game early.")
print("So, let's get started!")

#This calls the random number generator
random_number=[]
while len(random_number) != 4:
    random_number=random_list()

#This calls the game function
game_engine(random_number)